peer_normalization: 0.03  # 控制 peer_normalization_loss 的权重/系数
momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.

input_dim: 3072
hidden_dim: 3072
num_layers: 10

goodness_type: sum
theta: 2.0  # 决定产生 ff_loss 的 logits 是 squared_sum 还是 squared_mean.